# Generated by Django 5.0.7 on 2024-07-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('date_range', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/pfapp/assets/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
