# Generated by Django 5.0.7 on 2024-07-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0002_experience_alter_project_image_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=30)),
                ('field', models.CharField(max_length=30)),
                ('date_range', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='place',
            new_name='location',
        ),
    ]
