# Generated by Django 5.0.7 on 2024-07-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0003_education_rename_place_experience_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField(max_length=50)),
                ('skill2', models.CharField(max_length=50)),
                ('skill3', models.CharField(max_length=50)),
                ('skill4', models.CharField(max_length=50)),
                ('skill5', models.CharField(max_length=50)),
                ('skill6', models.CharField(max_length=50)),
            ],
        ),
    ]
