# Generated by Django 5.0.7 on 2024-07-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0004_professionalskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalskills',
            name='skill1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='skill2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='skill3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='skill4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='skill5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='skill6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
