# Generated by Django 5.0.7 on 2024-07-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0006_alter_professionalskills_skill1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalskills',
            name='skill1',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='skill2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='skill3',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='skill4',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='skill5',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='skill6',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
