# Generated by Django 5.0.7 on 2024-07-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapp', '0007_alter_professionalskills_skill1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('l2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('l3', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('l4', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('l5', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('l6', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
